# Generated by Django 2.2.1 on 2019-10-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('describe', models.CharField(max_length=255, verbose_name='描述')),
                ('show_time', models.DateTimeField(blank=True, null=True, verbose_name='显示时间')),
                ('hide_time', models.DateTimeField(blank=True, null=True, verbose_name='下架时间')),
                ('banner_h5', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Banner H5')),
                ('banner_pc', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Banner PC')),
                ('script_h5', models.TextField(blank=True, null=True, verbose_name='链接/脚本(h5)')),
                ('script_pc', models.TextField(blank=True, null=True, verbose_name='链接/脚本(pc)')),
                ('sort', models.IntegerField(default=1, verbose_name='排序')),
            ],
            options={
                'db_table': 'home_banner',
                'ordering': ['-sort'],
            },
        ),
    ]
