# Generated by Django 2.2.1 on 2019-10-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeBanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='show_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='显示时间'),
        ),
    ]
