# Generated by Django 2.2.1 on 2019-10-16 06:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HomeBanner', '0002_auto_20191016_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='show_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='显示时间'),
        ),
    ]
