# Generated by Django 2.2.1 on 2019-10-14 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('gameName', models.CharField(max_length=256, verbose_name='游戏名称')),
                ('gameID', models.CharField(blank=True, max_length=256, null=True, verbose_name='游戏ID')),
                ('platform', models.IntegerField(blank=True, choices=[(12, 'AG国际厅'), (27, 'AE厅'), (9, 'BBIN厅'), (30, 'CQ9厅'), (21, 'DT厅'), (23, 'PP厅'), (24, 'PS厅'), (15, 'PT厅'), (26, 'PT国际厅'), (35, 'PT亚洲厅'), (31, 'PNG厅'), (34, 'NT厅'), (17, 'MG国际厅'), (22, 'SW厅'), (18, 'TTG厅')], default=1, null=True, verbose_name='平台')),
                ('bet', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='投注金额')),
                ('awards', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='爆奖金额')),
                ('awardTime', models.DateField(verbose_name='中奖时间')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='bigWinImgs', verbose_name='图片')),
                ('isH5', models.BooleanField(default=False, verbose_name='是否H5')),
                ('isXiqi', models.BooleanField(default=False, verbose_name='是否红包')),
                ('name', models.CharField(default='', max_length=20, verbose_name='中奖用户名')),
            ],
            options={
                'db_table': 'bigwin_history',
            },
        ),
    ]
