# Generated by Django 2.2.1 on 2019-10-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BigWin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='平台名称')),
            ],
            options={
                'db_table': 'platform',
            },
        ),
    ]
