# Generated by Django 2.2.1 on 2019-10-28 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BigWin', '0002_auto_20191019_0909'),
        ('BigWin', '0002_platform'),
    ]

    operations = [
    ]
