# Generated by Django 2.2.4 on 2019-10-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('bankName', models.CharField(max_length=32, verbose_name='银行名称')),
                ('bankCode', models.CharField(max_length=32, verbose_name='银行代码')),
                ('isBan', models.BooleanField(default=False, verbose_name='是否禁用')),
                ('isMaintenance', models.BooleanField(default=False, verbose_name='是否禁用')),
            ],
            options={
                'db_table': 'sys_bank',
            },
        ),
    ]
